"""empty message

Revision ID: bcfddd0d95cb
Revises: 1eb0c6681e7a
Create Date: 2024-04-20 15:19:38.605495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcfddd0d95cb'
down_revision = '1eb0c6681e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_password_id'), 'password', ['id'])
    op.create_unique_constraint(op.f('uq_user_id'), 'user', ['id'])
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('uq_user_id'), 'user', type_='unique')
    op.drop_constraint(op.f('uq_password_id'), 'password', type_='unique')
    # ### end Alembic commands ###
